' Gambas module file

Public $dir As String

Public Sub setdir(dir As String)


  $dir = dir &/ "Nintendo/Contents/registered"


End

Public Sub look() As Collection

  Dim s As String
  Dim sPFile As String
  Dim Path As String[]
  Dim Size As Long[]
  Dim r As Collection
  Dim d As String
  Dim l As Long

  r = New Collection
  Path = New String[]
  Size = New Long[]

  For Each s In Dir($dir, "", gb.Directory)
    For Each sPFile In Dir($dir &/ s)
      If Stat($dir &/ s &/ sPFile).Type = gb.Directory Then
        l = 0
        For Each d In Dir($dir &/ s &/ sPFile)
          l += Stat($dir &/ s &/ sPFile &/ d).Size
        Next
        Size.Add(l)
      Else
        Size.Add(Stat($dir &/ s &/ sPFile).Size)
      Endif
      Path.Add($dir &/ s &/ sPFile)
    Next
  Next

  r.Add(Path, "Path")
  r.Add(Size, "Size")
  Return r

End
